/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_997727_4[] = { 0, 6, 12 };

// (before - mean) / scale
const float ei_classifier_anom_scale_997727_4[3] = { 1426.7396543006637, 1105.9190081311974, 553.2967762047033 };
const float ei_classifier_anom_mean_997727_4[3] = { 1534.2951735987933, 1057.6134168748918, 5210.084608352022 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_997727_4[32] = {
	{ ( float[3] ) { -0.8892536759376526, -0.91042160987854, -0.5697611570358276 }, 0.08846031280890046 },
	{ ( float[3] ) { -0.5428553223609924, 1.490419626235962, 0.008752021938562393 }, 0.854065987254214 },
	{ ( float[3] ) { 0.4111223518848419, -0.23256400227546692, 0.6841474175453186 }, 0.6529545209356598 },
	{ ( float[3] ) { -0.0037539456970989704, 0.9248632788658142, 0.5324409604072571 }, 0.9655511444064256 },
	{ ( float[3] ) { 0.15091858804225922, 2.5437352657318115, 0.8528794646263123 }, 0.899344088025307 },
	{ ( float[3] ) { 0.8075131773948669, -0.23675185441970825, -0.5594348311424255 }, 0.4694644025381978 },
	{ ( float[3] ) { 1.1774754524230957, -0.3190382421016693, -0.5969177484512329 }, 0.608773423146617 },
	{ ( float[3] ) { -0.5526869297027588, 0.963687002658844, 0.17505931854248047 }, 0.779594660852157 },
	{ ( float[3] ) { 1.710618495941162, -0.14935912191867828, -0.6263118386268616 }, 0.5950217161123202 },
	{ ( float[3] ) { 1.8957302570343018, 0.48249727487564087, -0.6079062223434448 }, 0.6739635147665816 },
	{ ( float[3] ) { -0.43965819478034973, -0.3445148468017578, 0.12886448204517365 }, 0.6995956556254052 },
	{ ( float[3] ) { -0.19284550845623016, 0.552120566368103, 1.5164763927459717 }, 0.6598405521053481 },
	{ ( float[3] ) { -0.2073562741279602, 0.8234615325927734, 1.1205382347106934 }, 0.5554997857054078 },
	{ ( float[3] ) { 0.5986437201499939, 3.6141891479492188, 1.5568046569824219 }, 1.0751474547052609 },
	{ ( float[3] ) { 1.1844843626022339, 0.1690688133239746, -0.589637279510498 }, 0.58499103900099 },
	{ ( float[3] ) { 0.22499175369739532, 2.2928855419158936, -0.22536490857601166 }, 0.6002848227027998 },
	{ ( float[3] ) { -0.3951285183429718, 1.1107937097549438, 1.972870945930481 }, 0.8144504964284901 },
	{ ( float[3] ) { 2.277506113052368, 0.046808090060949326, -0.6862660646438599 }, 0.5770577332945321 },
	{ ( float[3] ) { 3.1233878135681152, 0.7732797861099243, -0.8789896368980408 }, 0.6889589859942542 },
	{ ( float[3] ) { 0.33139923214912415, -0.2638636827468872, -0.4987655580043793 }, 0.5790711062563308 },
	{ ( float[3] ) { -0.31371983885765076, 0.4201391339302063, 0.804959237575531 }, 0.6649509908755862 },
	{ ( float[3] ) { 0.5957872271537781, 3.165891170501709, 3.0559489727020264 }, 1.0596729328448256 },
	{ ( float[3] ) { -0.2643849849700928, 1.7030380964279175, 3.5490076541900635 }, 0.8240718935131068 },
	{ ( float[3] ) { -0.0581696592271328, 2.021343231201172, 2.6182684898376465 }, 0.92000606631687 },
	{ ( float[3] ) { -0.5622861385345459, 1.3696205615997314, 0.8711391091346741 }, 0.579650683756913 },
	{ ( float[3] ) { -0.19977878034114838, 0.026515139266848564, -0.5388298630714417 }, 0.8186700521574841 },
	{ ( float[3] ) { -0.06454963982105255, 1.9457228183746338, 1.5014547109603882 }, 0.9819118444465826 },
	{ ( float[3] ) { -0.5480450391769409, -0.3040541112422943, 1.0768564939498901 }, 0.6906318894990703 },
	{ ( float[3] ) { 0.16323839128017426, 1.6218358278274536, 4.820404529571533 }, 0.7120006023009523 },
	{ ( float[3] ) { -0.017523108050227165, 0.49995020031929016, -0.05043203383684158 }, 0.6832904474073817 },
	{ ( float[3] ) { 0.3117336928844452, -0.19115613400936127, 1.6969324350357056 }, 0.7104425089244665 },
	{ ( float[3] ) { -0.4185953438282013, 2.5314950942993164, 4.858082294464111 }, 0.7311339913447977 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
